/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shoppingcart.app;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        System.out.println("Do you have eWallet?");

        boolean eWallet = sc.nextBoolean();

        Shop shop = new Shop();
        Customer customer;
        customer = new Customer("James");
        ArrayList<Items> itemList= new ArrayList<>();

        itemList.add(new Items("milk",70,123,4));
        itemList.add(new Items("apple",20,229,3));
        itemList.add(new Items("newspaper",5,13,6));


        ShoppingCart cart = new ShoppingCart();
        cart.setItems(itemList);
        customer.setCart(cart);

        shop.shopTransaction(customer,eWallet);



    }
}
